config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from . import views

urlpatterns = [
    path("", views.HomeView, name="home"),
    path("index/", views.index, name="index"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    path("genome_browser/", views.genome_browser, name="genome_browser"),
    path(
        "tutorial/", TemplateView.as_view(template_name="pages/tutorial.html"), name="tutorial"
    ),
    path("unauthorized", views.render_403, name="unauthorized"),
    path(
        "tech_corner/", TemplateView.as_view(template_name="pages/tech_corner.html"), name="tech_corner"
    ),
    path(
        "founders/", TemplateView.as_view(template_name="pages/founder.html"), name="founders"
    ),
    path(
        "statistics/", TemplateView.as_view(template_name="pages/statistics.html"), name="statistics"
    ),
    path(
        "ressources/", TemplateView.as_view(template_name="pages/ressources.html"), name="ressources"
    ),
    path(
        "download/", TemplateView.as_view(template_name="pages/download.html"), name="download"
    ),
    path(
        "citing/", views.citing, name="citing"
    ),
    path(
        "help/", TemplateView.as_view(template_name="pages/help.html"), name="help"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("sdap.users.urls", namespace="users")),
    path("groups/", include("sdap.groups.urls", namespace="groups")),
    path("files/", include("sdap.files.urls", namespace="files")),
    path("tools/", include("sdap.tools.urls", namespace="tools")),
    path("jobs/", include("sdap.jobs.urls", namespace="jobs")),
    path("studies/", include("sdap.studies.urls", namespace="studies")),
    
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

sdap/files/urls.py
from django.urls import path
from sdap.files import views


app_name = 'files'
# Define urls here
urlpatterns = [
    path('', views.index, name='index'),
    path('folder/<int:folderid>', views.subindex, name='subindex'),
    path('file/<int:fileid>', views.view_file, name='view_file'),
    path('file/<int:fileid>/visualize', views.get_visualization, name='get_visualization'),
    path('download/<int:fileid>', views.download_file, name='download_file'),
]

sdap/jobs/urls.py
from django.urls import path
from sdap.jobs import views


app_name = 'jobs'
# Define urls here
urlpatterns = [
    # ex: /jobs/
    path('', views.IndexView.as_view(), name='index'),
    path('running_jobs/', views.RunningJobsView.as_view(), name='running_jobs'),
    path('delete_job/<int:pk>', views.Delete_job, name='delete_job'),
    # ex: /jobs/5/
    # the 'name' value as called by the {% url %} template tag
    path('<int:pk>/result', views.DetailView, name='results'),
    path('<int:pk>/result/<str:file_name>', views.DownloadView, name='results_download'),
]

sdap/tools/urls.py
from django.urls import path
from sdap.tools import views

app_name = 'tools'
# Define urls here
urlpatterns = [
    # ex: /tools/
    path('', views.IndexView.as_view(), name='index'),
    # ex: /tools/5/
    # the 'name' value as called by the {% url %} template tag
    path('<int:toolid>/', views.DetailView, name='detail'),
]

sdap/files/forms.py
from django import forms

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout
from crispy_forms.bootstrap import FormActions

from django.core.validators import MaxValueValidator, MinValueValidator

class VisualisationArgumentForm(forms.Form):

    def __init__(self, *args, **kwargs):

        visu_type = kwargs.pop('visu_type', False)
        table = kwargs.pop('table', False)
        super(VisualisationArgumentForm, self).__init__(*args, **kwargs)

        if visu_type and (visu_type == "Pieplot" or visu_type == "Barplot"):
            self.fields['Yvalues'] = forms.IntegerField(validators=[
                MaxValueValidator(len(table.index)),
                MinValueValidator(0)
            ])

        self.helper = FormHelper(self)
        self.helper.form_id= "visualization_form"
        self.helper.form_method = 'POST'

sdap/jobs/forms.py
from django import forms
from django.core.validators import MinValueValidator, MaxValueValidator

class GenerateRandomUserForm(forms.Form):
    total = forms.IntegerField(
        validators=[
            MinValueValidator(50),
            MaxValueValidator(500)
        ]
    )

sdap/files/views.py
import os
from datetime import datetime

from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.views import View
from django.shortcuts import redirect
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.http import HttpResponse
from mimetypes import guess_type
from django.urls import reverse_lazy
from django.http import HttpResponseForbidden

from django.template.loader import render_to_string
from django.http import JsonResponse

import pandas as pd

from sdap.files.models import File, Folder
from .forms import VisualisationArgumentForm

# Create your views here.
def index(request):

    folders = Folder.objects.filter(
            created_by= request.user,
            folder=None
       ).order_by('-created_at')

    files = File.objects.filter(
            created_by= request.user,
            folder=None
        ).order_by('-created_at')

    context = {'folders': folders, 'files': files}

    return render(request, 'files/index.html', context)


def subindex(request, folderid):


    previous_folder = Folder.objects.filter(
            created_by= request.user,
            folders=folderid
       )

    if previous_folder:
        back_url = reverse('files:subindex', kwargs={'folderid': previous_folder[0].id})
    else:
        back_url = reverse('files:index')

    folders = Folder.objects.filter(
            created_by= request.user,
            folder=folderid
       ).order_by('-created_at')

    files = File.objects.filter(
            created_by= request.user,
            folder=folderid
        ).order_by('-created_at')

    context = {'folders': folders, 'files': files, 'back_url': back_url}

    return render(request, 'files/index.html', context)

def view_file(request, fileid):

    # Check perm
    file = get_object_or_404(File, id=fileid)

    if not has_permission(request.user, file):
        return redirect('403/')
    # Need to make a list of available visualization tools based on type
    v_types = {
        'TEXT': ['Raw'],
        'IMAGE': ['Raw'],
        'CSV': ['Table', 'Pieplot', 'Barplot']
    }
    context = {'types': v_types[file.type], 'file': file}
    return render(request, 'files/visualize.html', context)


def get_visualization(request, fileid):

    file = get_object_or_404(File, id=fileid)
    if not has_permission(request.user, file):
        return redirect('403/')

    data = {}

    if request.method == 'POST':
        # Need to check form
        data = show_data(file, request.POST)
    else:
        visu_type = request.GET.get('type', '')
        if not visu_type:
            return redirect('403/')

        if visu_type == "Raw" or visu_type == "Table":
            data['data_table'] = ""
            form = VisualisationArgumentForm()
            context = {'form': form}
            data['form'] = render_to_string('files/form.html',
                context,
                request=request
            )

        else:
            # What if it's not tab separated?
            # Check file existence
            df = pd.read_csv(file.file, sep=",")
            if request.GET.get('transpose', False):
                df = df.transpose()
            df_head = df.head()
            table_content = df_head.to_html(classes=["table","table-bordered","table-striped"], justify='center', max_cols=10)
            data['data_table'] = table_content
            form = VisualisationArgumentForm(visu_type=visu_type, table=df)
            context = {'form': form}
            data['form'] = render_to_string('files/form.html',
                context,
                request=request
            )
    return JsonResponse(data)

def has_permission(user,file):
    # TODO: Manage group permissions here
    has_permission = False
    if file.created_by == user:
        has_permission = True

    return has_permission

def download_file(request, fileid):
    file_object = get_object_or_404(File, pk=fileid)
    owner = file_object.created_by

    if owner != request.user :
        return HttpResponseForbidden()
    else :
        filename = file_object.file.name.split('/')[-1]
        response = HttpResponse(file_object.file, content_type='text/plain')
        response['Content-Disposition'] = 'attachment; filename=%s' % filename

        return response


def show_data(file, post_data):
    data = {}
    if file.type == "TEXT":
        content = ""
        with file.file.open('r') as f:
            for line in f.readlines():
                content += line + "<br>"
        data['content'] = content
    elif file.type == "IMAGE":
        content = "<img src='" + file.file.url + "'></img>"
        data['content'] = content
    elif file.type == "CSV":
        df = pd.read_csv(file.file, sep=",")
        if 'transposed' in post_data:
            df = df.transpose()
        if post_data['type'] == "Table":
            table_content = "<div class='table-responsive' >" + df.to_html(classes=["table","table-bordered","table-striped"], justify='center', max_cols=10) + "</div>"
            data['content'] = table_content
        elif post_data['type'] == "Pieplot":
            data['content'] = createJsonViewPiePlot(df, post_data["Yvalues"])
        elif post_data['type'] == "Barplot":
            data['content'] = createJsonViewBarPlot(df, post_data["Yvalues"])
    return data




def createJsonViewBarPlot(data, row_number):
    chart = {}
    chart['config']={'displaylogo':False,'modeBarButtonsToRemove':['toImage','zoom2d','pan2d','lasso2d','resetScale2d']}
    chart['layout'] = {'showlegend': False,'yaxis':{'tickfont':10},'hovermode': 'closest'}
    chart['data'] = {
        'type': "bar",
        'x': data.columns.to_list(),
        'y': data.iloc[int(row_number), :].values.tolist()
    }

    return chart


def createJsonViewPiePlot(data, row_number):
    chart = {}
    chart['config']={'displaylogo':False,'modeBarButtonsToRemove':['toImage','zoom2d','pan2d','lasso2d','resetScale2d']}
    chart['layout'] = {'showlegend': False,'yaxis':{'tickfont':10},'hovermode': 'closest'}
    chart['data'] = {
        'type': "pie",
        'labels': data.columns.to_list(),
        'values': data.iloc[int(row_number), :].values.tolist(),
        'textposition': 'inside'
    }
    return chart

sdap/groups/views.py
from django.contrib.auth import get_user_model
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils import timezone
from django.shortcuts import redirect
from guardian.shortcuts import get_perms, get_objects_for_group
from django.views.generic import CreateView
from django.contrib.auth.models import Group

from django.db.models import Q
from sdap.groups.forms import GroupCreateForm, GroupInvitationForm
from sdap.users.models import User, Notification
from django.template.loader import render_to_string
from django.http import JsonResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect

from sdap.studies.models import ExpressionStudy

# TODO : clear 403 page redirect (page with an explanation?)
def DetailView(request, grpid):
    group = request.user.groups.filter(id=grpid).get()

    if not group:
        return redirect('/unauthorized')

    data = {
        'group': group,
        'users': group.user_set.all(),
        'notifications': group.add_notifications.all(),
        'read_access': get_objects_for_group(group, 'view_expressionstudy', ExpressionStudy),
        'edit_access': get_objects_for_group(group, 'change_expressionstudy', ExpressionStudy)
    }
    return render(request, 'groups/group_detail.html', data)

def create_group(request):

    if not request.user.is_authenticated:
        return redirect('/unauthorized')

    data = {}
    if request.method == 'POST':
        form = GroupCreateForm(request.POST)
        if form.is_valid():
            object = form.save()
            object.ownership.owner = request.user
            object.ownership.save()
            object.user_set.add(request.user)
            data['redirect'] = reverse("groups:detail", kwargs={"grpid": object.id})
            data['form_is_valid'] = True
        else:
            data['form_is_valid'] = False
    else:
        form = GroupCreateForm()

    context = {'form': form}
    data['html_form'] = render_to_string('groups/partial_group_create.html',
        context,
        request=request,
    )

    return JsonResponse(data)

def send_invitation(request, group_id):
    group = get_object_or_404(Group, pk=group_id)
    users = User.objects.exclude(Q(groups=group) | Q(notifications__group=group) | Q(username="AnonymousUser")).all()

    if not request.user == group.ownership.owner:
         return redirect('/unauthorized')

    data = {}
    if request.method == 'POST':
        form = GroupInvitationForm(request.POST)

        if not form.is_valid():
            data['form_is_valid'] = False

        elif not users.filter(id=request.POST['user']).exists():
            form = GroupInvitationForm(users=users)
            data['form_is_valid'] = False
            data['error'] = "This user is either already in the group, or has already an invitation pending. Please select another."

        else:
            object = form.save(commit=False)
            object.created_by = request.user
            object.group = group
            object.type = "GROUP"
            object.message = "Invitation to the group " + group.name
            object.save()
            data['redirect'] = reverse("groups:detail", kwargs={"grpid": group_id})
            data['form_is_valid'] = True
    else:
        form = GroupInvitationForm(users=users)

    context = {'form': form, 'group': group}
    data['html_form'] = render_to_string('groups/partial_user_add.html',
        context,
        request=request,
    )

    return JsonResponse(data)

def set_owner(request, group_id, new_owner_id):
    group = get_object_or_404(Group, pk=group_id)
    # Check user is owner
    # And target is not owner
    if not request.user == group.ownership.owner:
         return redirect('/unauthorized')

    user = get_object_or_404(User, pk=new_owner_id)
    data = {}

    if request.method == 'POST':
        if not group.ownership.owner == user:
            group.ownership.owner = user
            group.ownership.save()

        data['redirect'] = reverse("groups:detail", kwargs={"grpid": group_id})
        data['form_is_valid'] = True
    else:
        context = {'group': group, 'user': user}
        data['html_form'] = render_to_string('groups/partial_owner_change.html',
            context,
            request=request,
         )
    return JsonResponse(data)

def remove_user_from_group(request, group_id, user_to_remove_id):
    group = get_object_or_404(Group, pk=group_id)
    # Check user is owner
    # And target is not owner

    user = get_object_or_404(User, pk=user_to_remove_id)

    if not request.user == group.ownership.owner and not request.user == user:
        return redirect('/unauthorized')

    if group.ownership.owner == user:
    # TODO: Give a proper error instead
        return redirect('/unauthorized')

    data = dict()
    if request.method == 'POST':
        group.user_set.remove(user)
        data['form_is_valid'] = True
        if request.user == user:
            data['redirect'] = reverse("users:detail", kwargs={"username": request.user.username})
        else:
            data['redirect'] = reverse("groups:detail", kwargs={"grpid": group.id})
    else:
        context = {'group': group, 'user': user, 'self': request.user == user}
        data['html_form'] = render_to_string('groups/partial_user_remove.html',
            context,
            request=request,
        )
    return JsonResponse(data)

sdap/templates/pages/about.html
{% extends "base.html" %}
{% load static i18n %}


{% block content %}
    <div class="container-fluid">
        <!-- Jumbotron -->
        <div class="card card-image" style="">
            <div class="text-center py-2 px-2">
                <div class="py-2">
            
                    <!-- Content -->
                    <h5 class="h5 red-text"><i class="fas fa-info"></i> About</h5>
                    <h2 class="card-title h2 my-2 py-2">About the Reprogenomics Viewer</h2>

                </div>
            </div>
        </div>
        <!-- Jumbotron -->

    </div>
    <div class="container">

        <div class="row my-5">
            <div class="col-md-6 mb-5">
                <h2>What is the ReproGenomics Viewer?</h2>
                <hr>
                <p>The ReproGenomics Viewer (RGV) is a multi- and cross-species genomic database for the visualization, mining and comparison of published omics data sets for the reproductive science community.
                    It was developed to assist scientists in the mining of a wide range of ultra-high-throughput reprogenomics data, including RNA and DNA sequencing data.
                    RGV allows hosting, visualization, and direct comparison of users’ data to published genomics studies as well as to relevant genetic variations linked to reproduction.
                    The ReproGenomics Viewer database currently hosts several landmark datasets in the field of reproductive biology from several model organisms.
                    Data sets have been curated, processed and conveniently organized into several categories including biological topics, technologies, species and publications.
                    These standardized data analysis procedures within the reproductive science community greatly facilitate comparisons of data sets.</p>
            </div>

            <div class="col-md-6 mb-5">
                <h2>Why should I submit my highthroughput data to the ReproGenomics Viewer?</h2>
                <hr>
                <p>Considerable worries have recently been raised regarding the lack of reproducibility of biomedical research.
                    Funding agencies, such as the National Institutes of Health (NIH), share this concern and discuss ways to enhance reproducibility by notably providing greater transparency of the data.
                    Journals and public funding agencies have thus begun to make public availability of raw data but also analyzed data a condition of publication or funding, respectively.<br>
                    In addition, we believe that it is also a matter of give and take, so to speak as making reprogenomics data available to the community:<br>
                    1- it will facilitate data comparison and the development of innovative tools;<br>
                    2- and, on the other hand, it will make your reprogenomics studies and publications more visible (as investigators will be able to compare their own data with yours) and it will thus boost citations of your scientific articles.</p>
            </div>
        </div>

        <div class="row my-5">
            <div class="col-md-6 mb-5">
                <h2>Is the ReproGenomics Viewer database intended to replace existing resources?</h2>
                <hr>
                <p>Of course it isn't! RGV neither intends to archive raw data such as GEO, nor to replace existing reprogenomics resources.
                    Instead, it aims at complementing them by acting as a distribution hub in which scientists can actively submit and share their highthroughput data with the community.</p>
            </div>
        
            <div class="col-md-6 mb-5">
                <h2>Future developments and perspectives</h2>
                <hr>
                <p>In the near future we will extend the scope of the RGV to keep pace with rapid technological, bioinformatics/genomic and biological/clinical advances in the reproductive sciences.
                    In concrete terms, we are currently planning four separate actions:<br>
                    1- we will gather other relevant data sets from a wide range of species in RGV to cover other reproductive biological topics. In this context, we encourage data submission from colleagues.<br>
                    2- we will be adding other genetic information related to reproductive disorders (such as GWAS and Quantitative trait loci information from diverse sources and diverse model organisms).<br>
                    3- we plan to develop community tools that will greatly facilitate collaborative work and stimulate the emergence of novel forms of collaboration in our research field.<br></p>
            </div>
        </div>
        
    </div>

{% endblock %}

sdap/templates/pages/home.html
{% extends "base.html" %}
{% load static i18n %}
{% load account socialaccount %}
{% load crispy_forms_tags %}
{% block content %}
    <script>
      gtag('config', 'UA-158824695-1', {
        'page_title' : 'homepage',
        'page_path': '/home'
      });
    </script>
    <!-- Page Content -->
    <div class="container">
        <section class="mt-5 wow fadeIn">

            <!--Grid row-->
            <div class="row align-items-center">

                <!--Grid column-->
                    <div class="col-md-6 mb-4">

                        <img src="{% static 'images/logo/RGVLogo_home_crop.png' %}" class="img-fluid align-middle" alt="">

                    </div>
                    <!--Grid column-->

                    <!--Grid column-->
                    <div class="col-md-6 mb-4">

                        <!-- Main heading -->
                        <h3 class="h3 mb-3">Welcome to RGV</h3>
                        <p><b>The ReproGenomics Viewer (RGV)</b> is a multi- and cross-species genomic database for the visualization, mining and comparison of published omics data sets for the reproductive science community.</p>
                        <!-- Main heading -->
                        <hr>
                        <p>
                        It was developed to assist scientists in the mining of a wide range of ultra-high-throughput reprogenomics data, including RNA and DNA sequencing data.
                        </p>

                        <!-- CTA -->
                        <a target="_blank" href="{% url 'studies:index' %}" class="btn btn-indigo btn-md">Start
                        </a>

                    </div>
                <!--Grid column-->

            </div>
            <!--Grid row-->

        </section>
        <!--Section: Main info-->

        <hr class="my-5">

        <section>

        <h3 class="h3 text-center mb-5">RGV tools</h3>

        <!--Grid row-->
        <div class="row wow fadeIn align-items-center">

          <!--Grid column-->
          <div class="col-lg-6 col-md-12 px-4">

            <!--First row-->
            <div class="row">
              <div class="col-1 mr-3">
                <i class="fas fa-dna fa-2x indigo-text"></i>
              </div>
              <div class="col-10" onmouseover="passageDeLaSouris('{% static 'images/home/home_genome_browser_ordi.png' %}')">
                <h5 class="feature-title">Genome browser</h5>
                <p class="grey-text">Navigate on chromosomes using a user-friendly genome browser</p>
              </div>
            </div>
            <!--/First row-->

            <div style="height:30px"></div>

            <!--Second row-->
            <div class="row">
              <div class="col-1 mr-3">
                <i class="far fa-chart-bar fa-2x blue-text"></i>
              </div>
              <div class="col-10" onmouseover="passageDeLaSouris('{% static 'images/home/home_scatter_ordi.png' %}')">
                <h5 class="feature-title">Scatter, Density & Violin plots</h5>
                <p class="grey-text">Explore complex datasets
                </p>
              </div>
            </div>
            <!--/Second row-->

            <div style="height:30px"></div>

            <!--Third row-->
            <div class="row">
              <div class="col-1 mr-3">
                <i class="far fa-window-restore fa-2x cyan-text"></i>
              </div>
              <div class="col-10" onmouseover="passageDeLaSouris('{% static 'images/home/home_layout_ordi.png' %}')">
                <h5 class="feature-title">Multi screen layout</h5>
                <p class="grey-text">Visualize all the information you need</p>
              </div>
            </div>
            <!--/Third row-->

            <div style="height:30px"></div>

            <!--Third four-->
            <div class="row">
              <div class="col-1 mr-3">
                <i class="fas fa-users fa-2x red-text"></i>
              </div>
              <div class="col-10" onmouseover="passageDeLaSouris('{% static 'images/home/home_login_ordi.png' %}')">
                <h5 class="feature-title">User space</h5>
                <p class="grey-text">Save your gene lists and display your data in RGV</p>
              </div>
            </div>
            <!--/Third four-->


          </div>
          <!--/Grid column-->

          <!--Grid column-->
          <div class="col-lg-6 col-md-12">
              <img id="hoover_img" src="{% static 'images/home/home_default_ordi.png' %}" class="img-fluid" alt="">
          </div>
          <!--/Grid column-->

        </div>
        <!--/Grid row-->

      </section>
      <!--Section: Main features & Quick Start-->

      <hr class="my-5">

      <!--Section: More-->
      <section>

        <h2 class="my-5 h3 text-center">Get Started</h2>

        <!--First row-->
        <div class="row features-small mt-5 wow fadeIn">

          <!--Grid column-->
          <div class="col-xl-3 col-lg-6">
            <!--Grid row-->
            <div class="row">
              <div class="col-2">
                <i class="fas fa-info fa-2x mb-1 indigo-text" aria-hidden="true"></i>
              </div>
              <div class="col-10 mb-2 pl-3">
                <a href="{% url 'help' %}" style="text-decoration: none;color: black;"><h5 class="feature-title font-bold mb-1">Help</h5></a>
                <p class="grey-text mt-2">Need some help?
                </p>
              </div>
            </div>
            <!--/Grid row-->
          </div>
          <!--/Grid column-->

          <!--Grid column-->
          <div class="col-xl-3 col-lg-6">
            <!--Grid row-->
            <div class="row">
              <div class="col-2">
                <i class="fas fa-graduation-cap fa-2x mb-1 indigo-text" aria-hidden="true"></i>
              </div>
              <div class="col-10 mb-2">
                <a class="disabled" href="{% url 'tutorial' %}" style="text-decoration: none;color: black;"><h5 class="feature-title font-bold mb-1">Tutorials</h5></a>
                <p class="grey-text mt-2">Learn how to use the ReproGenomics Viewer.
                </p>
              </div>
            </div>
            <!--/Grid row-->
          </div>
          <!--/Grid column-->

          <!--Grid column-->
          <div class="col-xl-3 col-lg-6">
            <!--Grid row-->
            <div class="row">
              <div class="col-2">
                <i class="fas fa-wrench fa-2x mb-1 indigo-text" aria-hidden="true"></i>
              </div>
              <div class="col-10 mb-2">
                <a href="{% url 'tech_corner' %}" style="text-decoration: none;color: black;"><h5 class="feature-title font-bold mb-1">Technical corner</h5></a>
                <p class="grey-text mt-2">Get more insights about whats happen behind the scenes.
                </p>
              </div>
            </div>
            <!--/Grid row-->
          </div>
          <!--/Grid column-->

          <!--Grid column-->
          <div class="col-xl-3 col-lg-6">
            <!--Grid row-->
            <div class="row">
              <div class="col-2">
                <i class="fas fa-table fa-2x mb-1 indigo-text" aria-hidden="true"></i>
              </div>
              <div class="col-10 mb-2">
                <a href="{% url 'studies:index' %}" style="text-decoration: none;color: black;"><h5 class="feature-title font-bold mb-1">Browse studies</h5></a>
                <p class="grey-text mt-2">Browse the ReproGenomics Viewer indexed datasets.</p>
              </div>
            </div>
            <!--/Grid row-->
          </div>
          <!--/Grid column-->

        </div>
        <!--/First row-->

       

      </section>
      <!--Section: More-->

       <hr class="my-5">

        <section>

            <h3 class="h3 text-center mb-5">RGV news</h3>

            <!--Grid row-->
            <div class="row wow fadeIn justify-content-center scrollable mb-5">

                <!--Grid column-->
                <div class="col-lg-8 col-md-12 px-4 ">
                  <a class="twitter-timeline" href="https://twitter.com/ReproGenoViewer?ref_src=twsrc%5Etfw">Tweets by ReproGenoViewer</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
                </div>
                <!--/Grid column-->

            
            </div>
            <!--/Grid row-->

      </section>
      <!--Section: Main features & Quick Start-->

    </div>
    <!-- /.container -->
{% endblock %}
{% block javascript %}
    {{ block.super }}
    <script>
        function passageDeLaSouris(url) {
          var elmt = document.getElementById("hoover_img"); 
          elmt.setAttribute('src', url);
        }
    </script>
{% endblock %}