config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from . import views

urlpatterns = [
    path("", views.HomeView, name="home"),
    path("index/", views.index, name="index"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    path("genome_browser/", views.genome_browser, name="genome_browser"),
    path(
        "tutorial/", TemplateView.as_view(template_name="pages/tutorial.html"), name="tutorial"
    ),
    path("unauthorized", views.render_403, name="unauthorized"),
    path(
        "tech_corner/", TemplateView.as_view(template_name="pages/tech_corner.html"), name="tech_corner"
    ),
    path(
        "founders/", TemplateView.as_view(template_name="pages/founder.html"), name="founders"
    ),
    path(
        "statistics/", TemplateView.as_view(template_name="pages/statistics.html"), name="statistics"
    ),
    path(
        "ressources/", TemplateView.as_view(template_name="pages/ressources.html"), name="ressources"
    ),
    path(
        "download/", TemplateView.as_view(template_name="pages/download.html"), name="download"
    ),
    path(
        "citing/", views.citing, name="citing"
    ),
    path(
        "help/", TemplateView.as_view(template_name="pages/help.html"), name="help"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("sdap.users.urls", namespace="users")),
    path("groups/", include("sdap.groups.urls", namespace="groups")),
    path("files/", include("sdap.files.urls", namespace="files")),
    path("tools/", include("sdap.tools.urls", namespace="tools")),
    path("jobs/", include("sdap.jobs.urls", namespace="jobs")),
    path("studies/", include("sdap.studies.urls", namespace="studies")),
    
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

sdap/files/urls.py
from django.urls import path
from sdap.files import views


app_name = 'files'
# Define urls here
urlpatterns = [
    path('', views.index, name='index'),
    path('folder/<int:folderid>', views.subindex, name='subindex'),
    path('file/<int:fileid>', views.view_file, name='view_file'),
    path('file/<int:fileid>/visualize', views.get_visualization, name='get_visualization'),
    path('download/<int:fileid>', views.download_file, name='download_file'),
]

sdap/jobs/urls.py
from django.urls import path
from sdap.jobs import views


app_name = 'jobs'
# Define urls here
urlpatterns = [
    # ex: /jobs/
    path('', views.IndexView.as_view(), name='index'),
    path('running_jobs/', views.RunningJobsView.as_view(), name='running_jobs'),
    path('delete_job/<int:pk>', views.Delete_job, name='delete_job'),
    # ex: /jobs/5/
    # the 'name' value as called by the {% url %} template tag
    path('<int:pk>/result', views.DetailView, name='results'),
    path('<int:pk>/result/<str:file_name>', views.DownloadView, name='results_download'),
]

sdap/studies/urls.py
from django.urls import path, re_path
from sdap.studies import views
from sdap.studies import autocompletes

app_name = 'studies'
# Define urls here
urlpatterns = [
    path('', views.index, name='index'),
    path('view/<int:stdid>', views.ExpressionStudyDetailView, name="study_view"),
    path('view/gene_list', views.get_gene_list, name="gene_list_view"),
    path('create/study', views.CreateExpressionStudyView.as_view(), name='study_create'),
    path('create/gene_list', views.create_gene_list, name='gene_list_create'),
    path('create/document/<int:stdid>', views.add_document, name='document_create'),
    path('edit/study/<int:stdid>', views.EditExpressionStudyView.as_view(), name='study_edit'),
    path('edit/gene_list/<int:genelistid>', views.edit_gene_list, name='gene_list_edit'),
    path('download/document/<int:documentid>', views.download_document, name='document_download'),
    path('delete/document/<int:documentid>', views.delete_document, name='document_delete'),
    path('delete/study/<int:stdid>', views.delete_study, name='study_delete'),
    path('delete/gene_list/<int:genelistid>', views.delete_gene_list, name='gene_list_delete'),
    path('select/table', views.render_table, name='render_table'),
    path('select/document', views.document_select, name='select_documents'),
    path('graph', views.show_graph, name='graph'),
    path('graph_data', views.get_graph_data, name="graph_data"),
    re_path(r'^gene-autocomplete/$', autocompletes.GeneAutocomplete.as_view(), name='gene-autocomplete'),
    path('gene/<int:gene_id>', views.get_gene, name="get_gene"),
    path('table/<int:document_id>', views.get_genes_values_table, name="get_genes_values_table"),
    path('ajax/get_stud_db', views.get_stud_db, name="get_stud_db"),
    path('ajax/group_info', views.get_group_info, name="group_info"),
    path('ajax/class_info', views.get_class_info, name="class_info"),
    path('ajax/autocomplete_genes/<str:taxonid>', views.autocomplete_genes, name="autocomplete_genes"),
    re_path(r'^ome-autocomplete/$', autocompletes.OmeAutocomplete.as_view(), name="ome-autocomplete"),
    re_path(r'^technology-autocomplete/$', autocompletes.TechnologyAutocomplete.as_view(), name="technology-autocomplete"),
    re_path(r'^experimental-design-autocomplete/$', autocompletes.ExperimentalDesignAutocomplete.as_view(), name="experimental-design-autocomplete"),
    re_path(r'^topic-autocomplete/$', autocompletes.TopicAutocomplete.as_view(), name="topic-autocomplete"),
    re_path(r'^tissue-autocomplete/$', autocompletes.TissueAutocomplete.as_view(), name="tissue-autocomplete"),
    re_path(r'^sex-autocomplete/$', autocompletes.SexAutocomplete.as_view(), name="sex-autocomplete"),
    re_path(r'^dev-stage-autocomplete/$', autocompletes.DevStageAutocomplete.as_view(), name="dev-stage-autocomplete"),
    re_path(r'^antibody-autocomplete/$', autocompletes.AntibodyAutocomplete.as_view(), name="antibody-autocomplete"),
    re_path(r'^mutant-autocomplete/$', autocompletes.MutantAutocomplete.as_view(), name="mutant-autocomplete"),
    re_path(r'^cell-sorted-autocomplete/$', autocompletes.CellSortedAutocomplete.as_view(), name="cell-sorted-autocomplete"),
    re_path(r'^topic-autocomplete/$', autocompletes.TopicAutocomplete.as_view(), name="topic-autocomplete"),
]

sdap/tools/urls.py
from django.urls import path
from sdap.tools import views

app_name = 'tools'
# Define urls here
urlpatterns = [
    # ex: /tools/
    path('', views.IndexView.as_view(), name='index'),
    # ex: /tools/5/
    # the 'name' value as called by the {% url %} template tag
    path('<int:toolid>/', views.DetailView, name='detail'),
]

sdap/files/views.py
import os
from datetime import datetime

from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.views import View
from django.shortcuts import redirect
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.http import HttpResponse
from mimetypes import guess_type
from django.urls import reverse_lazy
from django.http import HttpResponseForbidden

from django.template.loader import render_to_string
from django.http import JsonResponse

import pandas as pd

from sdap.files.models import File, Folder
from .forms import VisualisationArgumentForm

# Create your views here.
def index(request):

    folders = Folder.objects.filter(
            created_by= request.user,
            folder=None
       ).order_by('-created_at')

    files = File.objects.filter(
            created_by= request.user,
            folder=None
        ).order_by('-created_at')

    context = {'folders': folders, 'files': files}

    return render(request, 'files/index.html', context)


def subindex(request, folderid):


    previous_folder = Folder.objects.filter(
            created_by= request.user,
            folders=folderid
       )

    if previous_folder:
        back_url = reverse('files:subindex', kwargs={'folderid': previous_folder[0].id})
    else:
        back_url = reverse('files:index')

    folders = Folder.objects.filter(
            created_by= request.user,
            folder=folderid
       ).order_by('-created_at')

    files = File.objects.filter(
            created_by= request.user,
            folder=folderid
        ).order_by('-created_at')

    context = {'folders': folders, 'files': files, 'back_url': back_url}

    return render(request, 'files/index.html', context)

def view_file(request, fileid):

    # Check perm
    file = get_object_or_404(File, id=fileid)

    if not has_permission(request.user, file):
        return redirect('403/')
    # Need to make a list of available visualization tools based on type
    v_types = {
        'TEXT': ['Raw'],
        'IMAGE': ['Raw'],
        'CSV': ['Table', 'Pieplot', 'Barplot']
    }
    context = {'types': v_types[file.type], 'file': file}
    return render(request, 'files/visualize.html', context)


def get_visualization(request, fileid):

    file = get_object_or_404(File, id=fileid)
    if not has_permission(request.user, file):
        return redirect('403/')

    data = {}

    if request.method == 'POST':
        # Need to check form
        data = show_data(file, request.POST)
    else:
        visu_type = request.GET.get('type', '')
        if not visu_type:
            return redirect('403/')

        if visu_type == "Raw" or visu_type == "Table":
            data['data_table'] = ""
            form = VisualisationArgumentForm()
            context = {'form': form}
            data['form'] = render_to_string('files/form.html',
                context,
                request=request
            )

        else:
            # What if it's not tab separated?
            # Check file existence
            df = pd.read_csv(file.file, sep=",")
            if request.GET.get('transpose', False):
                df = df.transpose()
            df_head = df.head()
            table_content = df_head.to_html(classes=["table","table-bordered","table-striped"], justify='center', max_cols=10)
            data['data_table'] = table_content
            form = VisualisationArgumentForm(visu_type=visu_type, table=df)
            context = {'form': form}
            data['form'] = render_to_string('files/form.html',
                context,
                request=request
            )
    return JsonResponse(data)

def has_permission(user,file):
    # TODO: Manage group permissions here
    has_permission = False
    if file.created_by == user:
        has_permission = True

    return has_permission

def download_file(request, fileid):
    file_object = get_object_or_404(File, pk=fileid)
    owner = file_object.created_by

    if owner != request.user :
        return HttpResponseForbidden()
    else :
        filename = file_object.file.name.split('/')[-1]
        response = HttpResponse(file_object.file, content_type='text/plain')
        response['Content-Disposition'] = 'attachment; filename=%s' % filename

        return response


def show_data(file, post_data):
    data = {}
    if file.type == "TEXT":
        content = ""
        with file.file.open('r') as f:
            for line in f.readlines():
                content += line + "<br>"
        data['content'] = content
    elif file.type == "IMAGE":
        content = "<img src='" + file.file.url + "'></img>"
        data['content'] = content
    elif file.type == "CSV":
        df = pd.read_csv(file.file, sep=",")
        if 'transposed' in post_data:
            df = df.transpose()
        if post_data['type'] == "Table":
            table_content = "<div class='table-responsive' >" + df.to_html(classes=["table","table-bordered","table-striped"], justify='center', max_cols=10) + "</div>"
            data['content'] = table_content
        elif post_data['type'] == "Pieplot":
            data['content'] = createJsonViewPiePlot(df, post_data["Yvalues"])
        elif post_data['type'] == "Barplot":
            data['content'] = createJsonViewBarPlot(df, post_data["Yvalues"])
    return data




def createJsonViewBarPlot(data, row_number):
    chart = {}
    chart['config']={'displaylogo':False,'modeBarButtonsToRemove':['toImage','zoom2d','pan2d','lasso2d','resetScale2d']}
    chart['layout'] = {'showlegend': False,'yaxis':{'tickfont':10},'hovermode': 'closest'}
    chart['data'] = {
        'type': "bar",
        'x': data.columns.to_list(),
        'y': data.iloc[int(row_number), :].values.tolist()
    }

    return chart


def createJsonViewPiePlot(data, row_number):
    chart = {}
    chart['config']={'displaylogo':False,'modeBarButtonsToRemove':['toImage','zoom2d','pan2d','lasso2d','resetScale2d']}
    chart['layout'] = {'showlegend': False,'yaxis':{'tickfont':10},'hovermode': 'closest'}
    chart['data'] = {
        'type': "pie",
        'labels': data.columns.to_list(),
        'values': data.iloc[int(row_number), :].values.tolist(),
        'textposition': 'inside'
    }
    return chart

sdap/jobs/views.py
import os
from datetime import datetime

from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.views import View
from django.shortcuts import redirect
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.http import HttpResponse
from mimetypes import guess_type
from django.urls import reverse_lazy


from sdap.jobs.models import Job
from celery.result import AsyncResult

# Create your views here.
class IndexView(LoginRequiredMixin, generic.ListView):
    template_name = 'analyse/index.html'
    context_object_name = 'latest_analyse_list'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Job.objects.filter(
            created_at__lte=timezone.now()
        ).order_by('-created_at')[:5]

def DetailView(request, pk):
    job = get_object_or_404(Job, pk=pk)
    file_list = []
    
    for file in os.listdir(job.output):
        table_content=''
        info = os.path.splitext(file)
        if info[1] == ".matrix" or info[1] == ".tsv" or info[1] == ".info" or info[1] == ".list" :
            df = pd.read_csv(os.path.join(job.output, file), sep="\t")
            df_head = df.head()
            table_content = df_head.to_html(classes=["table", "table-bordered", "table-striped", "table-hover"])
        if info[1] == ".csv":
            df = pd.read_csv(os.path.join(job.output, file), sep=",")
            df_head = df.head()
            table_content = df_head.to_html(classes=["table", "table-bordered", "table-striped", "table-hover"])
        file_list.append({'name':info[0],'ext':info[1], 'table':table_content, 'file':file, 'path':os.path.join(job.output, file)})
    context = {'job':job, 'file_list':file_list}
    return render(request, 'jobs/results.html', context)


def DownloadView(request, pk, file_name):
    job = get_object_or_404(Job, pk=pk)
    file_path = os.path.join(job.output, file_name)

    with open(file_path, 'rb') as f:
        response = HttpResponse(f, content_type=guess_type(file_path)[0])
        response['Content-Length'] = len(response.content)
        return response


class RunningJobsView(LoginRequiredMixin, generic.ListView):
    model = Job
    template_name = 'jobs/running_jobs.html'
    
    def get_context_data(self, **kwargs):
        context = super(RunningJobsView, self).get_context_data(**kwargs)
        context['jobs_list'] = Job.objects.filter(created_by__exact=self.request.user.id)
        for job in context['jobs_list']:
            if job.status != "SUCCESS":
                job.status = AsyncResult(job.celery_task_id).state
                job.save()
        return context

def Delete_job(request, pk):
    job = get_object_or_404(Job, pk=pk)
    print(job)
    job.delete()
    context = {}
    context['jobs_list'] = Job.objects.filter(created_by__exact=request.user.id)
    for job in context['jobs_list']:
        if job.status != "SUCCESS":
            job.status = AsyncResult(job.celery_task_id).state
            job.save()

    return render(request, 'jobs/running_jobs.html', context)

sdap/templates/studies/document_select.html
{% extends "base.html" %}
{% load static i18n %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="container-fluid">
        <form id="document-form">
        Please select the document for study {{study.article}}
        <div class="table-responsive-xl">
            <table class="table">
                <thead>
                    <tr style="text-align:center;">
                        <th scope="col">Species</th>
                        <th scope="col">Technology</th>
                        <th scope="col">Document name</th>
                        <th scope="col">Select data</th>
                    </tr>
                </thead>
                <tbody>
                    {% for file in study.data.all %}
                    <tr style="text-align:center;">
                        <td>{{file.species.name}}</td>
                        <td>{{file.get_technology_display}}</td>
                        <td>{{file.name}}</td>
                        <td><a class="btn btn-info" href="{% url 'studies:graph' %}?study_id={{study.id}}&document_id={{file.id}}">
                            <i class="fa fa-external-link-alt" aria-hidden="true"></i>Select</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        </form>
        
    </div>
{% endblock %}

sdap/templates/studies/gene_list_create.html
{% extends "base.html" %}
{% load static i18n %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="container" style="margin-bottom:70px;">
        <h2>Create a new gene list</h2>
        {% crispy form %}
    </div>

{% endblock %}

{% block javascript %}
    {{ block.super }}
    {{ form.media }}
    <script src="{% static 'js/gene_list.js' %}"></script>    
{% endblock %}

sdap/templates/studies/gene_list_edit.html
{% extends "base.html" %}
{% load static i18n %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="container" style="margin-bottom:70px;">
        <h2>Edit gene list</h2>
        {% crispy form %}
    </div>
{% endblock %}

{% block javascript %}
    {{ block.super }}
    {{ form.media }}
    <script src="{% static 'js/gene_list.js' %}"></script>
{% endblock %}

sdap/templates/studies/index.html
{% extends "base.html" %}
{% load static i18n %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="container">
            <div class="bs-stepper">
                <div class="bs-stepper-header" role="tablist">
                    <!-- your steps here -->
                    <div class="step" data-target="#dataset-part">
                        <button type="button" class="step-trigger" role="tab" aria-controls="dataset-part" id="dataset-part-trigger">
                            <span class="bs-stepper-circle">1</span>
                            <span class="bs-stepper-label">Select dataset</span>
                        </button>
                    </div>
                    <div class="line"></div>
                    <div class="step" data-target="#analyse-part">
                        <button type="button" class="step-trigger" role="tab" aria-controls="analyse-part" id="analyse-part-trigger">
                            <span class="bs-stepper-circle">2</span>
                            <span class="bs-stepper-label">Select analyse</span>
                        </button>
                    </div>
                </div>
                <div class="bs-stepper-content">
                    <!-- your steps content here -->
                    <div id="dataset-part" class="content" role="tabpanel" aria-labelledby="dataset-part-trigger">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th scope="col">Selection</th>
                                    <th scope="col">Article</th>
                                    <th scope="col">PMID</th>
                                    <th scope="col">Species</th>
                                    <th scope="col">Topics</th>
                                    <th scope="col">Cells</th>
                                    <th scope="col">Samples</th>
                                </tr>
                            </thead>
                        
                            <tbody>
                                {% for study in studies %}
                                <tr>
                                    <td>
                                        <label>
                                            <input type="checkbox" id="study" class="study" value="{{ study.id}}" />
                                            <span> </span>
                                        </label>
                                    </td>
                                    <td>{{ study.article }}</td>
                                    <td>{{ study.pmid }}</td>
                                    <td>{{ study.species | join:"," }}</td>
                                    <td>{{ study.topics | join:"," }}</td>
                                    <td>{{ study.cell_sorted | join:"," }}</td>
                                    <td>{{ study.samples_count | join:"," }}</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>     
                    </div>
                </div>
            </div>
    </div>
    
{% endblock %}
{% block javascript %}
    {{ block.super }}
    <script>
        var stepper = new Stepper($('.bs-stepper')[0])
        var url_getdb_studies = "{% url 'studies:get_stud_db' %}";
        var url_get_datasets = "{% url 'studies:select_documents' %}";
        var url_display_data = "{% url 'studies:graph' %}";
    </script>
    <script src="{% static 'js/studies.js' %}"></script>
{% endblock %}

sdap/templates/studies/partial_document_table.html
<table>
    <thead>
        <tr>
            <th>Selection</th>
            <th>Database</th>
            <th>Article</th>
            <th>Dataset</th>
            <th>Action</th>
        </tr>
    </thead>

    <tbody>
        {% for study in studies %}
            {% for file in study.data.all %}
                <tr>
                    <td>
                        <label>
                            <input type="checkbox" id="dataset" class="dataset" value="{{ file.id }}" name="{{ study.id }}" />
                            <span> </span>
                        </label>
                    </td>
                    <td>{{ study.database }}</td>
                    <td>{{ study.article }}</td>
                    <td>{{ file.name }}</td>
                    <td><i class="material-icons">file_download</i></td>
                </tr>
            {% endfor %}
        {% endfor %}
    </tbody>
</table>  

sdap/templates/studies/partial_jbrowse_iframe.html
<div>
      <iframe
        src="{{jbrowse_url}}"
        style="border: 1px solid black"
        width=iframe_width
        height=iframe_height
      >
      </iframe>
</div>

sdap/templates/studies/partial_study_delete.html
<form method="post" action="{% url 'studies:study_delete' study.id %}" class="js-save-form">
  {% csrf_token %}
  <div class="modal-header">
    <h4 class="modal-title">Delete study</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body">
    <p class="lead">Are you sure you want to delete the study {{study.article}}?{% if study.data.count %} It will also delete {{ study.data.count }} document(s).{% endif %}</p>
  </div>
  <div class="modal-footer">
    <button type="submit" class="btn btn-danger">Delete study</button>
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
  </div>
</form>

sdap/templates/studies/study_details.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% load custom %}
{% block title %}Study: {{ study.article }}{% endblock %}

{% block content %}
<div class="container-fluid" id="study">
  <div class="row">
    <div class="col-md-3 ">
      <div class="list-group ">
          <a href="#tab1" data-toggle="tab" class="list-group-item list-group-item-action {{is_active.main}}">Overview</a>
          <a href="#tab2" data-toggle="tab" class="list-group-item list-group-item-action {{is_active.datasets}}">
            <i class="fas fa-external-link-alt"></i> Available dataset(s) <span class="badge badge-primary badge-pill">{{ study.data.count }}</span>
          </a>
          <a href="#tab3" data-toggle="tab" class="list-group-item list-group-item-action">
            <i class="fas fa-external-link-alt"></i> Available Jbrowse dataset(s) <span class="badge badge-primary badge-pill">{{ study.jbrowse_data.count }}</span>
          </a>
      </div>
    </div>
    <div class="col-md-9">
      <div class="tab-content card" style="text-align:center;">
        <div class="tab-pane text-style card-body {{is_active.main}}" id="tab1">
          {% print_val study.pmid "Pubmed ID" False %}
          {% print_val study.title "Article Name" False %}
          {% print_val study.abstract "Abstract" False  %}
          {% print_val study.publish_date "Publication data" False %}
          {% print_val study.authors "Authors" False %}
          {% print_val study.ome "Ome" %}
          {% print_val study.technology "Technologies" %}
          {% print_val study.species "Species" %}
          {% print_val study.experimental_design "Experimental design" %}
          {% print_val study.topics "Topics" %}
          {% print_val study.tissues "Tissues" %}
          {% print_val study.sex "Sex" %}
          {% print_val study.dev_stage "Developmental stage" %}
          {% print_val study.age "Age" %}
          {% print_val study.antibody "Antibody" %}
          {% print_val study.mutantd "Mutant" %}
          {% print_val study.cell_sorted "Cell sorted" %}
          {% print_val study.keywords "Keywords" %}
          {% print_val study.samples_count "Sample count" False %}
          {% if user == study.created_by and not study.status == 'PUBLIC' %}
          <p>
            <a type="button" class="btn btn-default btn-sm" href="{% url 'studies:study_edit' study.id %}"> <i class="fas fa-cog"></i> Edit study </a>
            <button type="button" class="btn btn-danger btn-sm js-get-form" data-url="{% url 'studies:study_delete' study.id %}"> <i class="fas fa-trash"></i> Delete study </button>
          </p>
          {% endif %}
          <br>
        </div>
        <div class="tab-pane text-style card-body {{is_active.datasets}}" id="tab2">
          <h3>Document(s) {% if has_edit_perm %}<button data-url="{% url 'studies:document_create' study.id %}" class="btn btn-info js-get-form float-right"><i class="fas fa-plus"></i></button>{% endif %}</h3>
          {% if study.data.exists %}
          <div class="table-responsive-xl">
              <table class="table table-hover">
                  <thead>
                      <tr style="text-align:center;">
                          <th scope="col">Name</th>
                          <th scope="col">Species</th>
                          <th scope="col">Technology</th>
                          <th scope="col">Actions</th>                          
                      </tr>
                  </thead>
                  <tbody>
                  {% for data in study.data.all %}
                    <tr style="text-align:center;">
                        <td>{{data.name}}</td>
                        <td>{{data.species.name }}</td>
                        <td>{{data.get_technology_display}}</td>
                        <td>
                            <a type="button" class="btn btn-default btn-sm" href="{% url 'studies:graph' %}?study_id={{study.id}}&document_id={{data.id}}"> <i class="fas fa-external-link-alt"></i> View </a>
                            <a type="button" class="btn btn-default btn-sm" href="{% url 'studies:document_download' data.id %}"> <i class="fas fa-download"></i> Download </a>
                            {% if has_edit_perm %}
                            <button type="button" data-url="{% url 'studies:document_delete' data.id %}" class="btn btn-danger btn-sm js-get-form"> <i class="fas fa-trash"></i> Delete</button>
                            {% endif %}
                        </td>
                    </tr>
                  {% endfor %}
                  </tbody>
                  <tr>
            </table>
          </div>
          {% else %}
          <br>
          <p>No datasets are associated with this study</p>
          {% endif %}
        </div>
        <div class="tab-pane text-style card-body" id="tab3">
          <h3>Jbrowse datasets(s)</h3>
          {% if study.jbrowse_data.exists %}
          <div class="table-responsive-xl">
              <table class="table table-hover">
                  <thead>
                      <tr style="text-align:center;">
                          <th scope="col">Species</th>
                          <th scope="col">Jbrowse</th>                          
                      </tr>
                  </thead>
                  <tbody>
                  {% for data in study.jbrowse_data.all %}
                    <tr style="text-align:center;">
                        <td>{{data.species.name }}</td>
                        <td>{% get_jbrowse_link data %}</td>
                    </tr>
                  {% endfor %}
                  </tbody>
                  <tr>
            </table>
          </div>
          {% else %}
          <br>
          <p>No jbrowse datasets are associated with this study</p>
          {% endif %}
        </div>
    </div>
  </div>
  <div class="modal fade" id="modal-group">
      <div class="modal-dialog"><div class="modal-content"></div></div>
  </div>
</div>
<br>
{% endblock content %}

{% block javascript %}
    {{ block.super }}
    <script src="{% static 'js/study_details.js' %}"></script>
{% endblock %}