config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from . import views

urlpatterns = [
    path("", views.HomeView, name="home"),
    path("index/", views.index, name="index"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    path("genome_browser/", views.genome_browser, name="genome_browser"),
    path(
        "tutorial/", TemplateView.as_view(template_name="pages/tutorial.html"), name="tutorial"
    ),
    path("unauthorized", views.render_403, name="unauthorized"),
    path(
        "tech_corner/", TemplateView.as_view(template_name="pages/tech_corner.html"), name="tech_corner"
    ),
    path(
        "founders/", TemplateView.as_view(template_name="pages/founder.html"), name="founders"
    ),
    path(
        "statistics/", TemplateView.as_view(template_name="pages/statistics.html"), name="statistics"
    ),
    path(
        "ressources/", TemplateView.as_view(template_name="pages/ressources.html"), name="ressources"
    ),
    path(
        "download/", TemplateView.as_view(template_name="pages/download.html"), name="download"
    ),
    path(
        "citing/", views.citing, name="citing"
    ),
    path(
        "help/", TemplateView.as_view(template_name="pages/help.html"), name="help"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("sdap.users.urls", namespace="users")),
    path("groups/", include("sdap.groups.urls", namespace="groups")),
    path("files/", include("sdap.files.urls", namespace="files")),
    path("tools/", include("sdap.tools.urls", namespace="tools")),
    path("jobs/", include("sdap.jobs.urls", namespace="jobs")),
    path("studies/", include("sdap.studies.urls", namespace="studies")),
    
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

sdap/files/urls.py
from django.urls import path
from sdap.files import views


app_name = 'files'
# Define urls here
urlpatterns = [
    path('', views.index, name='index'),
    path('folder/<int:folderid>', views.subindex, name='subindex'),
    path('file/<int:fileid>', views.view_file, name='view_file'),
    path('file/<int:fileid>/visualize', views.get_visualization, name='get_visualization'),
    path('download/<int:fileid>', views.download_file, name='download_file'),
]

sdap/groups/urls.py
from django.urls import path
from sdap.groups import views

app_name = "groups"
urlpatterns = [
    path('<int:grpid>/', views.DetailView, name='detail'),
    path('create/', views.create_group, name='create'),
    path('invite/<int:group_id>', views.send_invitation, name='invite_user'),
    path('<int:group_id>/remove/<int:user_to_remove_id>', views.remove_user_from_group, name='remove_user'),
    path('<int:group_id>/changeowner/<int:new_owner_id>', views.set_owner, name='change_owner'),
]

sdap/jobs/urls.py
from django.urls import path
from sdap.jobs import views


app_name = 'jobs'
# Define urls here
urlpatterns = [
    # ex: /jobs/
    path('', views.IndexView.as_view(), name='index'),
    path('running_jobs/', views.RunningJobsView.as_view(), name='running_jobs'),
    path('delete_job/<int:pk>', views.Delete_job, name='delete_job'),
    # ex: /jobs/5/
    # the 'name' value as called by the {% url %} template tag
    path('<int:pk>/result', views.DetailView, name='results'),
    path('<int:pk>/result/<str:file_name>', views.DownloadView, name='results_download'),
]

sdap/tools/urls.py
from django.urls import path
from sdap.tools import views

app_name = 'tools'
# Define urls here
urlpatterns = [
    # ex: /tools/
    path('', views.IndexView.as_view(), name='index'),
    # ex: /tools/5/
    # the 'name' value as called by the {% url %} template tag
    path('<int:toolid>/', views.DetailView, name='detail'),
]

sdap/files/forms.py
from django import forms

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout
from crispy_forms.bootstrap import FormActions

from django.core.validators import MaxValueValidator, MinValueValidator

class VisualisationArgumentForm(forms.Form):

    def __init__(self, *args, **kwargs):

        visu_type = kwargs.pop('visu_type', False)
        table = kwargs.pop('table', False)
        super(VisualisationArgumentForm, self).__init__(*args, **kwargs)

        if visu_type and (visu_type == "Pieplot" or visu_type == "Barplot"):
            self.fields['Yvalues'] = forms.IntegerField(validators=[
                MaxValueValidator(len(table.index)),
                MinValueValidator(0)
            ])

        self.helper = FormHelper(self)
        self.helper.form_id= "visualization_form"
        self.helper.form_method = 'POST'

sdap/files/views.py
import os
from datetime import datetime

from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.views import View
from django.shortcuts import redirect
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.http import HttpResponse
from mimetypes import guess_type
from django.urls import reverse_lazy
from django.http import HttpResponseForbidden

from django.template.loader import render_to_string
from django.http import JsonResponse

import pandas as pd

from sdap.files.models import File, Folder
from .forms import VisualisationArgumentForm

# Create your views here.
def index(request):

    folders = Folder.objects.filter(
            created_by= request.user,
            folder=None
       ).order_by('-created_at')

    files = File.objects.filter(
            created_by= request.user,
            folder=None
        ).order_by('-created_at')

    context = {'folders': folders, 'files': files}

    return render(request, 'files/index.html', context)


def subindex(request, folderid):


    previous_folder = Folder.objects.filter(
            created_by= request.user,
            folders=folderid
       )

    if previous_folder:
        back_url = reverse('files:subindex', kwargs={'folderid': previous_folder[0].id})
    else:
        back_url = reverse('files:index')

    folders = Folder.objects.filter(
            created_by= request.user,
            folder=folderid
       ).order_by('-created_at')

    files = File.objects.filter(
            created_by= request.user,
            folder=folderid
        ).order_by('-created_at')

    context = {'folders': folders, 'files': files, 'back_url': back_url}

    return render(request, 'files/index.html', context)

def view_file(request, fileid):

    # Check perm
    file = get_object_or_404(File, id=fileid)

    if not has_permission(request.user, file):
        return redirect('403/')
    # Need to make a list of available visualization tools based on type
    v_types = {
        'TEXT': ['Raw'],
        'IMAGE': ['Raw'],
        'CSV': ['Table', 'Pieplot', 'Barplot']
    }
    context = {'types': v_types[file.type], 'file': file}
    return render(request, 'files/visualize.html', context)


def get_visualization(request, fileid):

    file = get_object_or_404(File, id=fileid)
    if not has_permission(request.user, file):
        return redirect('403/')

    data = {}

    if request.method == 'POST':
        # Need to check form
        data = show_data(file, request.POST)
    else:
        visu_type = request.GET.get('type', '')
        if not visu_type:
            return redirect('403/')

        if visu_type == "Raw" or visu_type == "Table":
            data['data_table'] = ""
            form = VisualisationArgumentForm()
            context = {'form': form}
            data['form'] = render_to_string('files/form.html',
                context,
                request=request
            )

        else:
            # What if it's not tab separated?
            # Check file existence
            df = pd.read_csv(file.file, sep=",")
            if request.GET.get('transpose', False):
                df = df.transpose()
            df_head = df.head()
            table_content = df_head.to_html(classes=["table","table-bordered","table-striped"], justify='center', max_cols=10)
            data['data_table'] = table_content
            form = VisualisationArgumentForm(visu_type=visu_type, table=df)
            context = {'form': form}
            data['form'] = render_to_string('files/form.html',
                context,
                request=request
            )
    return JsonResponse(data)

def has_permission(user,file):
    # TODO: Manage group permissions here
    has_permission = False
    if file.created_by == user:
        has_permission = True

    return has_permission

def download_file(request, fileid):
    file_object = get_object_or_404(File, pk=fileid)
    owner = file_object.created_by

    if owner != request.user :
        return HttpResponseForbidden()
    else :
        filename = file_object.file.name.split('/')[-1]
        response = HttpResponse(file_object.file, content_type='text/plain')
        response['Content-Disposition'] = 'attachment; filename=%s' % filename

        return response


def show_data(file, post_data):
    data = {}
    if file.type == "TEXT":
        content = ""
        with file.file.open('r') as f:
            for line in f.readlines():
                content += line + "<br>"
        data['content'] = content
    elif file.type == "IMAGE":
        content = "<img src='" + file.file.url + "'></img>"
        data['content'] = content
    elif file.type == "CSV":
        df = pd.read_csv(file.file, sep=",")
        if 'transposed' in post_data:
            df = df.transpose()
        if post_data['type'] == "Table":
            table_content = "<div class='table-responsive' >" + df.to_html(classes=["table","table-bordered","table-striped"], justify='center', max_cols=10) + "</div>"
            data['content'] = table_content
        elif post_data['type'] == "Pieplot":
            data['content'] = createJsonViewPiePlot(df, post_data["Yvalues"])
        elif post_data['type'] == "Barplot":
            data['content'] = createJsonViewBarPlot(df, post_data["Yvalues"])
    return data




def createJsonViewBarPlot(data, row_number):
    chart = {}
    chart['config']={'displaylogo':False,'modeBarButtonsToRemove':['toImage','zoom2d','pan2d','lasso2d','resetScale2d']}
    chart['layout'] = {'showlegend': False,'yaxis':{'tickfont':10},'hovermode': 'closest'}
    chart['data'] = {
        'type': "bar",
        'x': data.columns.to_list(),
        'y': data.iloc[int(row_number), :].values.tolist()
    }

    return chart


def createJsonViewPiePlot(data, row_number):
    chart = {}
    chart['config']={'displaylogo':False,'modeBarButtonsToRemove':['toImage','zoom2d','pan2d','lasso2d','resetScale2d']}
    chart['layout'] = {'showlegend': False,'yaxis':{'tickfont':10},'hovermode': 'closest'}
    chart['data'] = {
        'type': "pie",
        'labels': data.columns.to_list(),
        'values': data.iloc[int(row_number), :].values.tolist(),
        'textposition': 'inside'
    }
    return chart

sdap/groups/views.py
from django.contrib.auth import get_user_model
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils import timezone
from django.shortcuts import redirect
from guardian.shortcuts import get_perms, get_objects_for_group
from django.views.generic import CreateView
from django.contrib.auth.models import Group

from django.db.models import Q
from sdap.groups.forms import GroupCreateForm, GroupInvitationForm
from sdap.users.models import User, Notification
from django.template.loader import render_to_string
from django.http import JsonResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect

from sdap.studies.models import ExpressionStudy

# TODO : clear 403 page redirect (page with an explanation?)
def DetailView(request, grpid):
    group = request.user.groups.filter(id=grpid).get()

    if not group:
        return redirect('/unauthorized')

    data = {
        'group': group,
        'users': group.user_set.all(),
        'notifications': group.add_notifications.all(),
        'read_access': get_objects_for_group(group, 'view_expressionstudy', ExpressionStudy),
        'edit_access': get_objects_for_group(group, 'change_expressionstudy', ExpressionStudy)
    }
    return render(request, 'groups/group_detail.html', data)

def create_group(request):

    if not request.user.is_authenticated:
        return redirect('/unauthorized')

    data = {}
    if request.method == 'POST':
        form = GroupCreateForm(request.POST)
        if form.is_valid():
            object = form.save()
            object.ownership.owner = request.user
            object.ownership.save()
            object.user_set.add(request.user)
            data['redirect'] = reverse("groups:detail", kwargs={"grpid": object.id})
            data['form_is_valid'] = True
        else:
            data['form_is_valid'] = False
    else:
        form = GroupCreateForm()

    context = {'form': form}
    data['html_form'] = render_to_string('groups/partial_group_create.html',
        context,
        request=request,
    )

    return JsonResponse(data)

def send_invitation(request, group_id):
    group = get_object_or_404(Group, pk=group_id)
    users = User.objects.exclude(Q(groups=group) | Q(notifications__group=group) | Q(username="AnonymousUser")).all()

    if not request.user == group.ownership.owner:
         return redirect('/unauthorized')

    data = {}
    if request.method == 'POST':
        form = GroupInvitationForm(request.POST)

        if not form.is_valid():
            data['form_is_valid'] = False

        elif not users.filter(id=request.POST['user']).exists():
            form = GroupInvitationForm(users=users)
            data['form_is_valid'] = False
            data['error'] = "This user is either already in the group, or has already an invitation pending. Please select another."

        else:
            object = form.save(commit=False)
            object.created_by = request.user
            object.group = group
            object.type = "GROUP"
            object.message = "Invitation to the group " + group.name
            object.save()
            data['redirect'] = reverse("groups:detail", kwargs={"grpid": group_id})
            data['form_is_valid'] = True
    else:
        form = GroupInvitationForm(users=users)

    context = {'form': form, 'group': group}
    data['html_form'] = render_to_string('groups/partial_user_add.html',
        context,
        request=request,
    )

    return JsonResponse(data)

def set_owner(request, group_id, new_owner_id):
    group = get_object_or_404(Group, pk=group_id)
    # Check user is owner
    # And target is not owner
    if not request.user == group.ownership.owner:
         return redirect('/unauthorized')

    user = get_object_or_404(User, pk=new_owner_id)
    data = {}

    if request.method == 'POST':
        if not group.ownership.owner == user:
            group.ownership.owner = user
            group.ownership.save()

        data['redirect'] = reverse("groups:detail", kwargs={"grpid": group_id})
        data['form_is_valid'] = True
    else:
        context = {'group': group, 'user': user}
        data['html_form'] = render_to_string('groups/partial_owner_change.html',
            context,
            request=request,
         )
    return JsonResponse(data)

def remove_user_from_group(request, group_id, user_to_remove_id):
    group = get_object_or_404(Group, pk=group_id)
    # Check user is owner
    # And target is not owner

    user = get_object_or_404(User, pk=user_to_remove_id)

    if not request.user == group.ownership.owner and not request.user == user:
        return redirect('/unauthorized')

    if group.ownership.owner == user:
    # TODO: Give a proper error instead
        return redirect('/unauthorized')

    data = dict()
    if request.method == 'POST':
        group.user_set.remove(user)
        data['form_is_valid'] = True
        if request.user == user:
            data['redirect'] = reverse("users:detail", kwargs={"username": request.user.username})
        else:
            data['redirect'] = reverse("groups:detail", kwargs={"grpid": group.id})
    else:
        context = {'group': group, 'user': user, 'self': request.user == user}
        data['html_form'] = render_to_string('groups/partial_user_remove.html',
            context,
            request=request,
        )
    return JsonResponse(data)

sdap/templates/groups/group_detail.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Group: {{ group.name }}{% endblock %}

{% block content %}
<div class="container-fluid">
  <div class="row">
    <div class="col-md-3 ">
      <div class="list-group ">
          <a href="#group_users" data-toggle="tab" class="list-group-item list-group-item-action active">Overview</a>
          <a href="#tab2" data-toggle="tab" class="list-group-item list-group-item-action">Sent invitation(s)  ({{ notifications.count }})</a>
          <a href="#tab3" data-toggle="tab" class="list-group-item list-group-item-action">Permissions</a>
        </div>
    </div>
    <div class="col-md-9">
      <div class="tab-content card" style="text-align:center;">
        <div class="tab-pane active text-style card-body" id="group_users">
          <h2>{{ group.name }}</h2>
          <br>
          <div class="table-responsive-xl">
              <table class="table table-hover">
                  <thead>
                      <tr style="text-align:center;">
                          <th scope="col">Username</th>
                          <th scope="col">Email</th>
                          <th scope="col">Group owner</th>
                          {% if group.ownership.owner == request.user %}
                          <th scope="col">Actions</th>
                          {% endif %}
                      </tr>
                  </thead>
                  <tbody>
                    {% for user in users %}
                    <tr style="text-align:center;">
                      <td>{{user.username}}</td>
                      <td>{{user.email}}</td>
                      {% if group.ownership.owner == user %}
                      <td><i class="fas fa-check"></i</td>
                      {% else %}
                      <td></td>
                      {% endif %}
                      {% if group.ownership.owner == request.user %}
                      <td>
                        <button type="button" class="btn btn-primary btn-sm js-change_owner" data-url="{% url 'groups:change_owner' group.id user.id %}"
                         {% if group.ownership.owner == user %} disabled data-toggle="tooltip" data-placement="top" title="You are already the owner" {% endif %} >
                           <i class="fas fa-crown"></i> Set owner
                         </button>
                        <button type="button" class="btn btn-danger btn-sm js-remove_user" data-url="{% url 'groups:remove_user' group.id user.id %}"
                        {% if group.ownership.owner == user %} disabled data-toggle="tooltip" data-placement="top" title="Owner cannot be removed from group" {% endif %} >
                           <i class="fas fa-trash"></i> Remove
                        </button>
                      </td>
                      {% endif %}
                    </tr>
                    {% endfor %}
                  </tbody>
                  <tr>
              </table>
              <button type="button" class="btn btn-success btn-sm js-invite_user" data-url="{% url 'groups:invite_user' group.id %}">
                 <i class="fas fa-user"></i> Invite user
              </button>
              <button type="button" class="btn btn-danger btn-sm js-remove_user" data-url="{% url 'groups:remove_user' group.id request.user.id %}"
                {% if group.ownership.owner == request.user %} disabled data-toggle="tooltip" data-placement="top" title="The owner cannot leave the group" {% endif %} >
                 <i class="fas fa-sign-out-alt"></i> Leave group
              </button>
            </div>
        </div>
        <div class="tab-pane text-style card-body" id="tab2">
          <h3>Sent invitation(s)</h3>
          {% if notifications %}
          <div class="table-responsive-xl">
              <table class="table table-hover">
                  <thead>
                      <tr style="text-align:center;">
                          <th scope="col">User</th>
                          <th scope="col">Sent by</th>
                          <th scope="col">Date</th>
                      </tr>
                  </thead>
                  <tbody>
                  {% for notification in notifications %}
                    <tr style="text-align:center;">
                        <td>{{notification.user.username}}</td>
                        <td>{{notification.created_by.username}}</td>
                        <td>{{notification.created_at | date}}</td>
                    </tr>
                  {% endfor %}
                  </tbody>
                  <tr>
            </table>
          </div>
          {% else %}
          <br>
          <p>No pending invitations</p>
          {% endif %}
        </div>
        <div class="tab-pane text-style card-body" id="tab3">
          <h3>Studies permissions</h3>
          {% if read_access %}
          <div class="table-responsive-xl">
              <table class="table table-hover">
                  <thead>
                      <tr style="text-align:center;">
                          <th scope="col">Study</th>
                          <th scope="col">Owner</th>
                          <th scope="col">Read access</th>
                          <th scope="col">Edit access</th>
                      </tr>
                  </thead>
                  <tbody>
                  {% for study in read_access %}
                    <tr style="text-align:center;">
                        <td>{{ study.article }}</td>
                        <td>{{study.created_by.username}}</td>
                        <td><i class="fas fa-check"></i></td>
                        {% if study in edit_access %}
                        <td><i class="fas fa-check"></i></td>
                        {% else %}
                        <td></td>
                        {% endif %}
                    </tr>
                  {% endfor %}
                  </tbody>
                  <tr>
            </table>
          </div>
        {% else %}
        <br>
        <p>This group does not have any specific access.</p>
        {% endif %}
        </div>
      </div>
    </div>
  </div>
  <div class="modal fade" id="modal-group">
      <div class="modal-dialog"><div class="modal-content"></div></div>
  </div>
</div>
<br>
{% endblock content %}

{% block javascript %}
    {{ block.super }}
    <script src="{% static 'js/groups.js' %}"></script>
{% endblock %}

sdap/templates/groups/partial_group_create.html
{% load crispy_forms_tags %}

<form method="post" action="{% url 'groups:create' %}" class="js-form">
  {% csrf_token %}
  <div class="modal-header">
    <h4 class="modal-title">Create a new group</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body">
    <p class="lead">Select your group name</p>
        {{ form|crispy }}
  </div>
  <div class="modal-footer">
    <button type="submit" class="btn btn-default">Create group</button>
    <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
  </div>
</form>

sdap/templates/groups/partial_owner_change.html
<form method="post" action="{% url 'groups:change_owner' group.id user.id %}" class="js-owner-change-form">
  {% csrf_token %}
  <div class="modal-header">
    <h4 class="modal-title">Confirm owner change</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body">
    <p class="lead">Are you sure you want to set {{user}} as owner of the group {{group}} ? You will lose editing permissions</p>
  </div>
  <div class="modal-footer">
    <button type="submit" class="btn btn-danger">Change owner</button>
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
  </div>
</form>

sdap/templates/groups/partial_user_add.html
{% load crispy_forms_tags %}
<form method="post" action="{% url 'groups:invite_user' group.id %}" class="js-invite-user-form">
  {% csrf_token %}
  <div class="modal-header">
    <h4 class="modal-title">Send a group invitation</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body">
    <p id="error" style="color:red;"></p>
    <p class="lead">Select a user to invite</p>
        {{ form|crispy }}
  </div>
  <div class="modal-footer">
    <button type="submit" class="btn btn-default">Send invitation</button>
    <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
  </div>
</form>

sdap/templates/groups/partial_user_remove.html
<form method="post" action="{% url 'groups:remove_user' group.id user.id %}" class="js-user-remove-form">
  {% csrf_token %}
  <div class="modal-header">
    <h4 class="modal-title">Confirm removal from group</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body">
    {% if self %}
    <p class="lead">Are you sure you want to leave the group {{group.name}} ? You will lose access to all content restricted to it.</p>
    {% else %}
    <p class="lead">Are you sure you want to remove {{user.username}} from the group {{group.name}} ?</p>
    {% endif %}
  </div>
  <div class="modal-footer">
    {% if self %}
    <button type="submit" class="btn btn-danger">Leave group</button>
    {% else %}
    <button type="submit" class="btn btn-danger">Remove user</button>
    {% endif %}
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
  </div>
</form>