config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from . import views

urlpatterns = [
    path("", views.HomeView, name="home"),
    path("index/", views.index, name="index"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    path("genome_browser/", views.genome_browser, name="genome_browser"),
    path(
        "tutorial/", TemplateView.as_view(template_name="pages/tutorial.html"), name="tutorial"
    ),
    path("unauthorized", views.render_403, name="unauthorized"),
    path(
        "tech_corner/", TemplateView.as_view(template_name="pages/tech_corner.html"), name="tech_corner"
    ),
    path(
        "founders/", TemplateView.as_view(template_name="pages/founder.html"), name="founders"
    ),
    path(
        "statistics/", TemplateView.as_view(template_name="pages/statistics.html"), name="statistics"
    ),
    path(
        "ressources/", TemplateView.as_view(template_name="pages/ressources.html"), name="ressources"
    ),
    path(
        "download/", TemplateView.as_view(template_name="pages/download.html"), name="download"
    ),
    path(
        "citing/", views.citing, name="citing"
    ),
    path(
        "help/", TemplateView.as_view(template_name="pages/help.html"), name="help"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("sdap.users.urls", namespace="users")),
    path("groups/", include("sdap.groups.urls", namespace="groups")),
    path("files/", include("sdap.files.urls", namespace="files")),
    path("tools/", include("sdap.tools.urls", namespace="tools")),
    path("jobs/", include("sdap.jobs.urls", namespace="jobs")),
    path("studies/", include("sdap.studies.urls", namespace="studies")),
    
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

sdap/files/urls.py
from django.urls import path
from sdap.files import views


app_name = 'files'
# Define urls here
urlpatterns = [
    path('', views.index, name='index'),
    path('folder/<int:folderid>', views.subindex, name='subindex'),
    path('file/<int:fileid>', views.view_file, name='view_file'),
    path('file/<int:fileid>/visualize', views.get_visualization, name='get_visualization'),
    path('download/<int:fileid>', views.download_file, name='download_file'),
]

sdap/groups/urls.py
from django.urls import path
from sdap.groups import views

app_name = "groups"
urlpatterns = [
    path('<int:grpid>/', views.DetailView, name='detail'),
    path('create/', views.create_group, name='create'),
    path('invite/<int:group_id>', views.send_invitation, name='invite_user'),
    path('<int:group_id>/remove/<int:user_to_remove_id>', views.remove_user_from_group, name='remove_user'),
    path('<int:group_id>/changeowner/<int:new_owner_id>', views.set_owner, name='change_owner'),
]

sdap/jobs/urls.py
from django.urls import path
from sdap.jobs import views


app_name = 'jobs'
# Define urls here
urlpatterns = [
    # ex: /jobs/
    path('', views.IndexView.as_view(), name='index'),
    path('running_jobs/', views.RunningJobsView.as_view(), name='running_jobs'),
    path('delete_job/<int:pk>', views.Delete_job, name='delete_job'),
    # ex: /jobs/5/
    # the 'name' value as called by the {% url %} template tag
    path('<int:pk>/result', views.DetailView, name='results'),
    path('<int:pk>/result/<str:file_name>', views.DownloadView, name='results_download'),
]

sdap/studies/urls.py
from django.urls import path, re_path
from sdap.studies import views
from sdap.studies import autocompletes

app_name = 'studies'
# Define urls here
urlpatterns = [
    path('', views.index, name='index'),
    path('view/<int:stdid>', views.ExpressionStudyDetailView, name="study_view"),
    path('view/gene_list', views.get_gene_list, name="gene_list_view"),
    path('create/study', views.CreateExpressionStudyView.as_view(), name='study_create'),
    path('create/gene_list', views.create_gene_list, name='gene_list_create'),
    path('create/document/<int:stdid>', views.add_document, name='document_create'),
    path('edit/study/<int:stdid>', views.EditExpressionStudyView.as_view(), name='study_edit'),
    path('edit/gene_list/<int:genelistid>', views.edit_gene_list, name='gene_list_edit'),
    path('download/document/<int:documentid>', views.download_document, name='document_download'),
    path('delete/document/<int:documentid>', views.delete_document, name='document_delete'),
    path('delete/study/<int:stdid>', views.delete_study, name='study_delete'),
    path('delete/gene_list/<int:genelistid>', views.delete_gene_list, name='gene_list_delete'),
    path('select/table', views.render_table, name='render_table'),
    path('select/document', views.document_select, name='select_documents'),
    path('graph', views.show_graph, name='graph'),
    path('graph_data', views.get_graph_data, name="graph_data"),
    re_path(r'^gene-autocomplete/$', autocompletes.GeneAutocomplete.as_view(), name='gene-autocomplete'),
    path('gene/<int:gene_id>', views.get_gene, name="get_gene"),
    path('table/<int:document_id>', views.get_genes_values_table, name="get_genes_values_table"),
    path('ajax/get_stud_db', views.get_stud_db, name="get_stud_db"),
    path('ajax/group_info', views.get_group_info, name="group_info"),
    path('ajax/class_info', views.get_class_info, name="class_info"),
    path('ajax/autocomplete_genes/<str:taxonid>', views.autocomplete_genes, name="autocomplete_genes"),
    re_path(r'^ome-autocomplete/$', autocompletes.OmeAutocomplete.as_view(), name="ome-autocomplete"),
    re_path(r'^technology-autocomplete/$', autocompletes.TechnologyAutocomplete.as_view(), name="technology-autocomplete"),
    re_path(r'^experimental-design-autocomplete/$', autocompletes.ExperimentalDesignAutocomplete.as_view(), name="experimental-design-autocomplete"),
    re_path(r'^topic-autocomplete/$', autocompletes.TopicAutocomplete.as_view(), name="topic-autocomplete"),
    re_path(r'^tissue-autocomplete/$', autocompletes.TissueAutocomplete.as_view(), name="tissue-autocomplete"),
    re_path(r'^sex-autocomplete/$', autocompletes.SexAutocomplete.as_view(), name="sex-autocomplete"),
    re_path(r'^dev-stage-autocomplete/$', autocompletes.DevStageAutocomplete.as_view(), name="dev-stage-autocomplete"),
    re_path(r'^antibody-autocomplete/$', autocompletes.AntibodyAutocomplete.as_view(), name="antibody-autocomplete"),
    re_path(r'^mutant-autocomplete/$', autocompletes.MutantAutocomplete.as_view(), name="mutant-autocomplete"),
    re_path(r'^cell-sorted-autocomplete/$', autocompletes.CellSortedAutocomplete.as_view(), name="cell-sorted-autocomplete"),
    re_path(r'^topic-autocomplete/$', autocompletes.TopicAutocomplete.as_view(), name="topic-autocomplete"),
]

sdap/tools/urls.py
from django.urls import path
from sdap.tools import views

app_name = 'tools'
# Define urls here
urlpatterns = [
    # ex: /tools/
    path('', views.IndexView.as_view(), name='index'),
    # ex: /tools/5/
    # the 'name' value as called by the {% url %} template tag
    path('<int:toolid>/', views.DetailView, name='detail'),
]

sdap/users/urls.py
from django.urls import path

from sdap.users.views import (
    user_list_view,
    user_redirect_view,
    user_update_view,
    user_detail_view,
    dismiss_notification,
    accept_group_invitation
)

app_name = "users"
urlpatterns = [
    path("", view=user_list_view, name="list"),
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
    path("notification/dismiss/<int:notification_id>", view=dismiss_notification, name="dismiss_notification"),
    path("notification/accept/<int:notification_id>", view=accept_group_invitation, name="accept_group_invitation"),
]

sdap/files/forms.py
from django import forms

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout
from crispy_forms.bootstrap import FormActions

from django.core.validators import MaxValueValidator, MinValueValidator

class VisualisationArgumentForm(forms.Form):

    def __init__(self, *args, **kwargs):

        visu_type = kwargs.pop('visu_type', False)
        table = kwargs.pop('table', False)
        super(VisualisationArgumentForm, self).__init__(*args, **kwargs)

        if visu_type and (visu_type == "Pieplot" or visu_type == "Barplot"):
            self.fields['Yvalues'] = forms.IntegerField(validators=[
                MaxValueValidator(len(table.index)),
                MinValueValidator(0)
            ])

        self.helper = FormHelper(self)
        self.helper.form_id= "visualization_form"
        self.helper.form_method = 'POST'

sdap/groups/forms.py
from django import forms

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout
from crispy_forms.bootstrap import FormActions

from django.contrib.auth.models import Group
from sdap.users.models import Notification

class GroupCreateForm(forms.ModelForm):

    class Meta:
        model = Group
        fields = ["name"]

    def __init__(self, *args, **kwargs):
        super(GroupCreateForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_method = 'POST'
        self.helper.add_input(Submit('save', 'Save'))

class GroupInvitationForm(forms.ModelForm):

    class Meta:
        model = Notification
        fields = ["user"]

    def __init__(self, *args, **kwargs):
        users = kwargs.pop('users', None)
        super(GroupInvitationForm, self).__init__( *args, **kwargs)
        if users:
            self.fields['user'].queryset = users
        else:
            self.fields['user'].widget.attrs['disabled'] = True
            self.fields['user'].label = "All users are already invited or members of the group."

sdap/jobs/forms.py
from django import forms
from django.core.validators import MinValueValidator, MaxValueValidator

class GenerateRandomUserForm(forms.Form):
    total = forms.IntegerField(
        validators=[
            MinValueValidator(50),
            MaxValueValidator(500)
        ]
    )

sdap/files/views.py
import os
from datetime import datetime

from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.views import View
from django.shortcuts import redirect
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.http import HttpResponse
from mimetypes import guess_type
from django.urls import reverse_lazy
from django.http import HttpResponseForbidden

from django.template.loader import render_to_string
from django.http import JsonResponse

import pandas as pd

from sdap.files.models import File, Folder
from .forms import VisualisationArgumentForm

# Create your views here.
def index(request):

    folders = Folder.objects.filter(
            created_by= request.user,
            folder=None
       ).order_by('-created_at')

    files = File.objects.filter(
            created_by= request.user,
            folder=None
        ).order_by('-created_at')

    context = {'folders': folders, 'files': files}

    return render(request, 'files/index.html', context)


def subindex(request, folderid):


    previous_folder = Folder.objects.filter(
            created_by= request.user,
            folders=folderid
       )

    if previous_folder:
        back_url = reverse('files:subindex', kwargs={'folderid': previous_folder[0].id})
    else:
        back_url = reverse('files:index')

    folders = Folder.objects.filter(
            created_by= request.user,
            folder=folderid
       ).order_by('-created_at')

    files = File.objects.filter(
            created_by= request.user,
            folder=folderid
        ).order_by('-created_at')

    context = {'folders': folders, 'files': files, 'back_url': back_url}

    return render(request, 'files/index.html', context)

def view_file(request, fileid):

    # Check perm
    file = get_object_or_404(File, id=fileid)

    if not has_permission(request.user, file):
        return redirect('403/')
    # Need to make a list of available visualization tools based on type
    v_types = {
        'TEXT': ['Raw'],
        'IMAGE': ['Raw'],
        'CSV': ['Table', 'Pieplot', 'Barplot']
    }
    context = {'types': v_types[file.type], 'file': file}
    return render(request, 'files/visualize.html', context)


def get_visualization(request, fileid):

    file = get_object_or_404(File, id=fileid)
    if not has_permission(request.user, file):
        return redirect('403/')

    data = {}

    if request.method == 'POST':
        # Need to check form
        data = show_data(file, request.POST)
    else:
        visu_type = request.GET.get('type', '')
        if not visu_type:
            return redirect('403/')

        if visu_type == "Raw" or visu_type == "Table":
            data['data_table'] = ""
            form = VisualisationArgumentForm()
            context = {'form': form}
            data['form'] = render_to_string('files/form.html',
                context,
                request=request
            )

        else:
            # What if it's not tab separated?
            # Check file existence
            df = pd.read_csv(file.file, sep=",")
            if request.GET.get('transpose', False):
                df = df.transpose()
            df_head = df.head()
            table_content = df_head.to_html(classes=["table","table-bordered","table-striped"], justify='center', max_cols=10)
            data['data_table'] = table_content
            form = VisualisationArgumentForm(visu_type=visu_type, table=df)
            context = {'form': form}
            data['form'] = render_to_string('files/form.html',
                context,
                request=request
            )
    return JsonResponse(data)

def has_permission(user,file):
    # TODO: Manage group permissions here
    has_permission = False
    if file.created_by == user:
        has_permission = True

    return has_permission

def download_file(request, fileid):
    file_object = get_object_or_404(File, pk=fileid)
    owner = file_object.created_by

    if owner != request.user :
        return HttpResponseForbidden()
    else :
        filename = file_object.file.name.split('/')[-1]
        response = HttpResponse(file_object.file, content_type='text/plain')
        response['Content-Disposition'] = 'attachment; filename=%s' % filename

        return response


def show_data(file, post_data):
    data = {}
    if file.type == "TEXT":
        content = ""
        with file.file.open('r') as f:
            for line in f.readlines():
                content += line + "<br>"
        data['content'] = content
    elif file.type == "IMAGE":
        content = "<img src='" + file.file.url + "'></img>"
        data['content'] = content
    elif file.type == "CSV":
        df = pd.read_csv(file.file, sep=",")
        if 'transposed' in post_data:
            df = df.transpose()
        if post_data['type'] == "Table":
            table_content = "<div class='table-responsive' >" + df.to_html(classes=["table","table-bordered","table-striped"], justify='center', max_cols=10) + "</div>"
            data['content'] = table_content
        elif post_data['type'] == "Pieplot":
            data['content'] = createJsonViewPiePlot(df, post_data["Yvalues"])
        elif post_data['type'] == "Barplot":
            data['content'] = createJsonViewBarPlot(df, post_data["Yvalues"])
    return data




def createJsonViewBarPlot(data, row_number):
    chart = {}
    chart['config']={'displaylogo':False,'modeBarButtonsToRemove':['toImage','zoom2d','pan2d','lasso2d','resetScale2d']}
    chart['layout'] = {'showlegend': False,'yaxis':{'tickfont':10},'hovermode': 'closest'}
    chart['data'] = {
        'type': "bar",
        'x': data.columns.to_list(),
        'y': data.iloc[int(row_number), :].values.tolist()
    }

    return chart


def createJsonViewPiePlot(data, row_number):
    chart = {}
    chart['config']={'displaylogo':False,'modeBarButtonsToRemove':['toImage','zoom2d','pan2d','lasso2d','resetScale2d']}
    chart['layout'] = {'showlegend': False,'yaxis':{'tickfont':10},'hovermode': 'closest'}
    chart['data'] = {
        'type': "pie",
        'labels': data.columns.to_list(),
        'values': data.iloc[int(row_number), :].values.tolist(),
        'textposition': 'inside'
    }
    return chart

sdap/templates/users/partial_notif_dismiss.html
<form method="post" action="{% url 'users:dismiss_notification' notification.id %}" class="js-form">
  {% csrf_token %}
  <div class="modal-header">
    <h4 class="modal-title">Refuse group invitation</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body">
    <p class="lead">Are you sure you want to refuse this invitation to the group {{group.name}}? You will not be able to access data restricted to this group.</p>
  </div>
  <div class="modal-footer">
    <button type="submit" class="btn btn-danger">Dismiss invitation</button>
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
  </div>
</form>

sdap/templates/users/user_detail.html
{% extends "base.html" %}
{% load custom %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<div class="container">
    <h2 class="m-y-2">Profile</h2>
    <div class="row m-y-2">
        <div class="col-lg-12 push-lg-12">
            <ul class="nav nav-tabs">
                <li class="nav-item">
                    <a href="" data-target="#profile" data-toggle="tab" class="nav-link {{in_use.user}}">Profile</a>
                </li>
                {% if object == request.user %}
                <li class="nav-item">
                    <a href="" data-target="#notifications" data-toggle="tab" class="nav-link {{in_use.notification}}">Notifications ({{ notifications.paginator.count }})</a>
                </li>
                <li class="nav-item">
                    <a href="" data-target="#groups" data-toggle="tab" class="nav-link {{in_use.group}}">My groups  ({{ groups.paginator.count }})</a>
                </li>
                <li class="nav-item">
                    <a href="" data-target="#studies" data-toggle="tab" class="nav-link {{in_use.study}}">My studies  ({{ studies.paginator.count }})</a>
                </li>
                <li class="nav-item">
                    <a href="" data-target="#gene_lists" data-toggle="tab" class="nav-link {{in_use.gene_list}}">My gene lists  ({{ gene_lists.paginator.count }})</a>
                </li>
                {% endif %}
            </ul>
            <div class="tab-content p-b-3" style="margin-top:20px;">
                <div class="tab-pane {{in_use.user}}" id="profile">
                    <div class="row">
                      <div class="col-md-12">
                        <form>
                          <div class="form-group">
                            <label for="exampleInputUser">User name</label>
                            <input type="text" class="form-control" id="exampleInputUser" aria-describedby="UserHelp" placeholder="" value="{{ object.username }}" disabled>
                            <small id="UserHelp" class="form-text text-muted">Can't be modified</small>
                          </div>
                          <div class="form-group">
                            <label for="exampleInputmail">Email</label>
                            <input type="text" class="form-control" id="exampleInputmail" aria-describedby="MailHelp" placeholder="" value="{{ object.email }}" disabled>
                          </div>
                          <div class="form-group">
                            <label for="exampleInputFirst">First name</label>
                            <input type="text" class="form-control" id="exampleInputFirst" aria-describedby="FirstHelp" placeholder="Enter email" value="{{ object.name }}" disabled>
                          </div>
                          <div class="form-group">
                            <label for="exampleInputLast">Last name</label>
                            <input type="text" class="form-control" id="exampleInputLast" aria-describedby="LastHelp" placeholder="Click on modify to change your last name" value="{{ object.last_name }}" disabled>
                          </div>
                          <div class="form-group">
                            <label for="exampleInputCompagny">Institut</label>
                            <input type="text" class="form-control" id="exampleInputCompagny" placeholder="Click on modify to change your compagny" value="{{ object.institut }}" disabled>
                          </div>
                        </form>
                        {% if object == request.user %}
                        <!-- Action buttons -->
                        <div class="row">

                          <div class="col-sm-12">
                            <a class="btn btn-outline-info" href="{% url 'users:update' %}" role="button">Edit info</a>
                            <a class="btn btn-outline-info" href="{% url 'account_email' %}" role="button">E-Mail</a>
                            <!-- Your Stuff: Custom user template urls -->
                          </div>

                        </div>
                        <!-- End Action buttons -->
                        {% endif %}
                      </div>
                    </div>
                </div>
                {% if object == request.user %}
                <div class="tab-pane {{in_use.notification}}" id="notifications">
                <h2>My notifications</h2>
                <div class="table-responsive-xl">
                    <table class="table table-hover" id="notification_list">
                        <thead>
                            <tr style="text-align:center;">
                                <th scope="col">Sent by</th>
                                <th scope="col">Message</th>
                                <th scope="col">Action</th>
                            </tr>
                        </thead>
                    <tbody>
                        {% for notification in notifications %}
                        <tr style="text-align:center;">
                            <td>{{notification.created_by}}</td>
                            <td>{{notification.message}}</td>
                            <td>
                                {% if notification.type == 'GROUP' %}
                                <button type="button" class="btn btn-success btn-sm js-notif-action" data-url="{% url 'users:accept_group_invitation' notification.id %}">
                                <span class="glyphicon glyphicon-trash"></span> Accept
                                </button>
                                <button type="button" class="btn btn-danger btn-sm js-refuse-invitation" data-url="{% url 'users:dismiss_notification' notification.id %}">
                                <span class="glyphicon glyphicon-trash"></span> Dismiss
                                </button>
                                {% else %}
                                <button type="button" class="btn btn-danger btn-sm js-notif-action" data-url="{% url 'users:dismiss_notification' notification.id %}">
                                <span class="glyphicon glyphicon-trash"></span> Dismiss
                                </button>
                                {% endif %}
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                    </table>
                    {% if notifications %}
                    {% with table=notifications type="notifications" %}
                    {% include "pages/paginate.html" %}
                    {% endwith %}
                    {% endif %}
                </div>
                </div>
                <div class="tab-pane {{in_use.group}}" id="groups">
                <h2>My groups <button data-url="{% url 'groups:create' %}" class="btn btn-outline-info js-create float-right"><i class="fas fa-external-link-alt"></i>New</button></h2>
                <div class="table-responsive-xl">
                    <table class="table table-hover">
                        <thead>
                            <tr style="text-align:center;">
                                <th scope="col">Name</th>
                                <th scope="col">Members</th>
                                <th scope="col">Group owner?</th>
                            </tr>
                        </thead>
                    <tbody>
                        {% for group in groups %}
                        <tr style="text-align:center;">
                            <td><a href="{% url 'groups:detail' group.id %}">{{group.name}}</a></td>
                            <td>{{group.members_number}}</td>
                            {% if group.ownership.owner == request.user %}
                            <td><i class="fas fa-check"></i></td>
                            {% else %}
                            <td>{{group.ownership.owner.username}}</td>
                            {% endif %}
                        </tr>
                        {% endfor %}
                    </tbody>
                    </table>
                    {% if groups %}
                    {% with table=groups type="groups" %}
                    {% include "pages/paginate.html" %}
                    {% endwith %}
                    {% endif %}
                </div>
                </div>
                <div class="tab-pane {{in_use.study}}" id="studies">
                <h2>My studies <a href="{% url 'studies:study_create' %}" class="btn btn-outline-info float-right"><i class="fas fa-external-link-alt"></i>New</a></h2>
                <div class="table-responsive-xl">
                    <table class="table table-hover">
                        <thead>
                            <tr style="text-align:center;">
                                <th scope="col">Pubmed ID</th>
                                <th scope="col">Article</th>
                                <th scope="col">Species</th>
                                <th scope="col">Technology</th>
                                <th scope="col">Documents</th>
                                <th scope="col">Status</th>
                            </tr>
                        </thead>
                        <tbody>
                          {% for study in studies %}
                          <tr style="text-align:center;">
                            <th><a href="{% url 'studies:study_view' study.id %}" style="color:#007bff"><b>{{study.pmid}}</b></a></th>
                            <td>{{study.article}}</td>
                            <td>{{study.species | join:",<br>"}}</td>
                            <td>{{study.technology | join:",<br>"}}</td>
                            <td>{{study.data.count}}</td>
                            <td>{{study.status}}</td>
                          </tr>
                          {% endfor %}
                        </tbody>
                    </table>
                    {% if studies %}
                    {% with table=studies type="studies" %}
                    {% include "pages/paginate.html" %}
                    {% endwith %}
                    {% endif %}
                </div>
                </div>
                <div class="tab-pane {{in_use.gene_list}}" id="gene_lists">
                <h2>My gene lists <a href="{% url 'studies:gene_list_create' %}" class="btn btn-outline-info float-right"><i class="fas fa-external-link-alt"></i>New</a></h2>
                <div class="table-responsive-xl">
                    <table class="table table-hover">
                        <thead>
                            <tr style="text-align:center;">
                                <th scope="col">Name</th>
                                <th scope="col">Species</th>
                                <th scope="col">Genes</th>
                                <th scope="col"></th>
                            </tr>
                        </thead>
                        <tbody>
                          {% for gene_list in gene_lists %}
                          <tr style="text-align:center;">
                            <th>{{gene_list.name}}</th>
                            <td>{{gene_list.species.name}}</td>
                            <td>
                            {% for gene in gene_list.genes.all %}
                                {{gene.symbol}} ({{gene.gene_id}}){% if not forloop.last %}, {% endif %}
                            {% endfor %}
                            </td>
                            <td>
                                <a href="{% url 'studies:gene_list_edit' gene_list.id %}" class="btn btn-info">Edit</a>
                                <a href="{% url 'studies:gene_list_delete' gene_list.id %}" class="btn btn-danger">Delete</a>
                           </td>
                          </tr>
                          {% endfor %}
                        </tbody>
                    </table>
                    {% if gene_lists %}
                    {% with table=gene_lists type="gene_lists" %}
                    {% include "pages/paginate.html" %}
                    {% endwith %}
                    {% endif %}
                </div>
                </div>
               </div>
               {% endif %}
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="modal-group">
    <div class="modal-dialog">
        <div class="modal-content"></div>
    </div>
</div>
<hr>
</div>


{% endblock content %}

{% block javascript %}
    {{ block.super }}
    <script>var token = '{{ csrf_token }}';</script>
    <script src="{% static 'js/user.js' %}"></script>
{% endblock %}

sdap/templates/users/user_list.html
{% extends "base.html" %}
{% load static i18n %}
{% block title %}Members{% endblock %}

{% block content %}
<div class="container">
  <h2>Users</h2>

  <div class="list-group">
    {% for user in user_list %}
      <a href="{% url 'users:detail' user.username %}" class="list-group-item">
        <h4 class="list-group-item-heading">{{ user.username }}</h4>
      </a>
    {% endfor %}
  </div>
</div>
{% endblock content %}